### ISSUE TITLE
这个有没有节约内存的办法

### ISSUE THREAD

**Issue by xxllp** [chenyuntc/PyTorchText#1]
看说明是要32G内存

**Comment by chenyuntc** [comment]
抱歉，才看到，以前github有issue明明会给我发邮件的。。。

就数据处理那一步需要，你可以直接下载预处理之后的数据（train.npz），其它的数据预处理都很快
https://www.floydhub.com/viewer/data/Ziy7UyUvHmL8QzCr6umuSU/

**Comment by zhhongzhi** [comment]
我的24G可以，把每个del 后面加上gc.collect()，比如
```
import gc
del es
gc.collect()
```
我不确定原来的版本在24G下可不可以，没有试。
ps: 上边的下载链接不可用了。

**Comment by w5688414** [comment]
@ 可以分享以下你生成的train.npz,我32GB的内存按照你的方式添加了，还是memory error

**Comment by w5688414** [comment]
@zhhongzhi  可以分享以下你生成的train.npz,我32GB的内存按照你的方式添加了，还是memory error
