### ISSUE TITLE
请问des3 文件的解压密码是?

### ISSUE THREAD

**Issue by timlincool** [chenyuntc/PyTorchText#2]
等比赛结束看到报导才过来的
想请问一个问题

目前官网只剩下des3 链接了 rar 已经不提供
https://www.dropbox.com/s/auycv8lt6ntd805/ieee_zhihu_cup.des3?dl=0

想请问des3 文件的解压密码是?

**Comment by chenyuntc** [comment]
抱歉，才看到，以前github有issue明明会给我发邮件的。。。

提取码好象是 5f3q
