### ISSUE TITLE
请问词向量转成numpy数组，你这个word2vec怎么装的？

### ISSUE THREAD

**Issue by ynuwm** [chenyuntc/PyTorchText#5]
我怎么没有这个包，pip也不能安装

**Comment by ynuwm** [comment]
我用em = gensim.models.KeyedVectors.load_word2vec_format(em_file) 可以导入embedding文件，问题是后面怎么写。
vec = (em.vectors)
word2id = em.vocab_hash
这两个怎么得到

**Comment by chenyuntc** [comment]
https://github.com/danielfrg/word2vec
