### ISSUE TITLE
where is your word2vec module?

### ISSUE THREAD

**Issue by ShawnXiha** [chenyuntc/PyTorchText#6]
in embedding2matrix.py there is the code
`
import word2vec
import numpy as np

def main(em_file, em_result):
    '''
    embedding ->numpy
    '''
    em = word2vec.load(em_file)
    vec = (em.vectors)
    word2id = em.vocab_hash
    # d = dict(vector = vec, word2id = word2id)
    # t.save(d,em_result)
    np.savez_compressed(em_result,vector=vec,word2id=word2id)

if __name__ == '__main__':
    import fire
    fire.Fire()
`

but I can not find any module named 'word2vec'

thank you

**Comment by chenyuntc** [comment]
Hi, It's fixed via [this commit](https://github.com/chenyuntc/PyTorchText/commit/4de55ba0dab60f522fb28693ea6fa2c9b587cf65)
